version: '2.3'
services:
  redis:
    build:
      context: containers/redis
    volumes:
      - redis:/data
    restart: always
    command: "redis-server --appendonly yes --loadmodule /usr/local/lib/rebloom.so"
    expose:
      - 6379

  tor:
    build:
      context: containers/tor
    restart: always
    environment:
      privoxy: 1
      haproxy_pass: thisisnotsecureatallbutitisbetterthanplainadmin
      test_url: http://example.com
      test_status: 200
    expose:
      - 8118
      - 5566
      - 2090

  spider:
      build:
          context: .
      restart: always
      environment:
        REDIS_HOST: redis
        REDIS_PORT: 6379
        SOCKS_PROXY: socks5://tor:5566
      env_file: .env
      command: "python torspider"
      depends_on:
        - redis
        - tor

volumes:
  redis:
    driver: local
