version: '2.3'
services:
  redis:
    build:
      context: containers/redis
    volumes:
      - /mnt/nfs/torspider/redis:/data
    restart: always
    command: "redis-server --appendonly yes --loadmodule /usr/local/lib/rebloom.so"
    expose:
      - 6379

  tor:
    build:
      context: containers/tor
    restart: always
    environment:
      haproxy_pass: thisisnotsecureatallbutitisbetterthanplainadmin
    expose:
      - 8118
      - 5566
      - 2090

  spider:
    build:
        context: .
    restart: always
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SOCKS_PROXY: http://tor:5566
      CELERY_BROKER: redis://redis:6379/1
      CELERY_RESULT: redis://redis:6379/1
    volumes:
      - /mnt/nfs/torspider/data:/data
    env_file: .env
    command: "python torspider"
    depends_on:
      - redis
      - tor

  celery:
    build: .
    restart: always
    command: celery -A spidercommon.tasks -P gevent --autoscale=16,8 worker
    links:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CELERY_BROKER: redis://redis:6379/1
      CELERY_RESULT: redis://redis:6379/1
    volumes:
      - /mnt/nfs/torspider/data:/data
    env_file: .env

  beat:
    build: .
    restart: always
    command: celery -A spidercommon.tasks beat
    links:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CELERY_BROKER: redis://redis:6379/1
      CELERY_RESULT: redis://redis:6379/1
    env_file: .env
