"""blacklisted field

Revision ID: 1c98a11a06db
Revises: b22cbc26d295
Create Date: 2018-01-05 05:31:45.564144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c98a11a06db'
down_revision = 'b22cbc26d295'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domains', sa.Column('blacklisted', sa.Boolean(), server_default='f', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domains', 'blacklisted')
    # ### end Alembic commands ###
