"""indexes

Revision ID: 46a49c045b7c
Revises: 9b6cb1883857
Create Date: 2017-12-14 16:35:23.231321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a49c045b7c'
down_revision = '9b6cb1883857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('index_domain_host', 'domains', ['host'], unique=False)
    op.create_index('index_page_domain_id', 'pages', ['domain_id'], unique=False)
    op.create_index('index_page_url', 'pages', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('index_page_url', table_name='pages')
    op.drop_index('index_page_domain_id', table_name='pages')
    op.drop_index('index_domain_host', table_name='domains')
    # ### end Alembic commands ###
