"""alive domain

Revision ID: 60f8471d8dcb
Revises: da7d39075bca
Create Date: 2018-01-02 14:05:45.051478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60f8471d8dcb'
down_revision = 'da7d39075bca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domains', sa.Column('alive', sa.Boolean(), server_default='f', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domains', 'alive')
    # ### end Alembic commands ###
