"""files table

Revision ID: 79bca7a97e8f
Revises: 6fb08b2110a1
Create Date: 2018-01-16 04:15:52.788156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79bca7a97e8f'
down_revision = '6fb08b2110a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Unicode(), nullable=False),
    sa.Column('path', sa.Unicode(), nullable=True),
    sa.Column('first_crawl', sa.DateTime(), nullable=False),
    sa.Column('last_crawl', sa.DateTime(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('index_file_domain_id', 'files', ['domain_id'], unique=False)
    op.create_index('index_file_url', 'files', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('index_file_url', table_name='files')
    op.drop_index('index_file_domain_id', table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
