"""compressed content

Revision ID: 7f4065c8cbef
Revises: 46a49c045b7c
Create Date: 2017-12-15 14:51:36.872634

"""
from alembic import op
import sqlalchemy as sa
from spidercommon.model import sm, Page


# revision identifiers, used by Alembic.
revision = '7f4065c8cbef'
down_revision = '46a49c045b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('content_compressed', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###

    # Manually run the commit.
    conn = op.get_bind()
    conn.execute("COMMIT")

    # Actually do the migration.
    db = sm()
    done = 0
    print("Starting compression conversion process.")
    for page in db.query(Page):
        if done % 10 == 0:
            print(f"Compressed {done} pages.")
            db.commit()
        if page.content:
            page.set_content(page.content)
        done += 1
    db.commit()


def downgrade():
    raise Exception("no goin back")
