"""page unique url

Revision ID: 863d9f3dcb59
Revises: bfdc24740b12
Create Date: 2018-04-08 23:07:04.528544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863d9f3dcb59'
down_revision = 'bfdc24740b12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'pages', ['url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pages', type_='unique')
    # ### end Alembic commands ###
