"""path

Revision ID: 9b6cb1883857
Revises: e1dbe116cf79
Create Date: 2017-12-14 12:33:12.284633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b6cb1883857'
down_revision = 'e1dbe116cf79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('path', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'path')
    # ### end Alembic commands ###
