"""hash method

Revision ID: b22cbc26d295
Revises: d307012eb130
Create Date: 2018-01-02 23:53:26.100738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b22cbc26d295'
down_revision = 'd307012eb130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onion_blacklist', sa.Column('hashmethod', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('onion_blacklist', 'hashmethod')
    # ### end Alembic commands ###
