"""remove page content column

Revision ID: bfdc24740b12
Revises: e222b8f8a112
Create Date: 2018-04-08 19:55:50.852308

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bfdc24740b12'
down_revision = 'e222b8f8a112'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('content', postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
