"""previous hashes column

Revision ID: e222b8f8a112
Revises: ff92f36a4c13
Create Date: 2018-01-16 16:19:14.520087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e222b8f8a112'
down_revision = 'ff92f36a4c13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('previous_hashes', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'previous_hashes')
    # ### end Alembic commands ###
