"""content as files

Revision ID: ff92f36a4c13
Revises: 79bca7a97e8f
Create Date: 2018-01-16 15:46:41.307894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff92f36a4c13'
down_revision = '79bca7a97e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'status_code')
    op.drop_column('pages', 'size')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
